name: Main Branch Pipeline
on:
  workflow_call:
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
jobs:
  UNIT-TESTS:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo npm test

  build:
    runs-on: self-hosted
    needs: UNIT-TESTS
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo docker build

  DEV:
    runs-on: self-hosted
    needs: build
    environment: DEV
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  QA:
    runs-on: self-hosted
    needs: DEV
    environment: QA
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  E2E-TESTS:
    runs-on: self-hosted
    needs: DEV
    environment: QA
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  UAT:
    runs-on: self-hosted
    needs: QA
    environment: E2E-TESTS
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  PROD:
    runs-on: self-hosted
    needs: UAT
    environment: PROD
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo
##
